/*
 * generated by Xtext 2.12.0
 */
package nl.mrtnstn.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ScriptRuntimeModule extends AbstractScriptRuntimeModule {
}
